### ISSUE TITLE
ElasticSearch Indexing

### ISSUE THREAD

**Issue by durrentom** [alfonsomga/symfony.demo.on.roids#12]
Hi,

Thanks a lot for this great project, it helped me a lot. 
One thing I don't understand though is why the elastic search index is not updated when I create a new post?
I have to manually update it with the command console. 

I looked at the FOSElasticaBundle doc and it seems to be fine. I tried to change the config regarding the listeners but no success. What am I missing?

Thanks

**Comment by alfonsomga** [comment]
Hey @durrentom, you are right, I totally missed that part.

This should solve this issue:
```yml
listener:
    insert: true
    update: true
    delete: true
```

Thank you for let me know about that issue, now it's fixed.

**Comment by durrentom** [comment]
Thanks, I just tried but it did not solve it. I cleared the cache but no change.
Does it work on your end?

**Comment by alfonsomga** [comment]
Yeah, it's working.
Did you clear cache using ``app/console cache:clear --env=prod`?

Anyways I would recommend you to destroy your current Vagrant image and reinstall it.

**Comment by alfonsomga** [comment]
I'll investigate more about this issue and fix it.

**Comment by durrentom** [comment]
Ok I did a full reinstall and it works like a charm now. Thanks a lot!

**Comment by alfonsomga** [comment]
@durrentom You're welcome! :+1:
